# Site settings
title: Yuki
header-img: img/01.jpg
email: Princessqyy@gmail.com
copyright_name: Yuki
description: "This blog is mainly for coding and technical communicating!"

url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  PrincessQyy
#facebook_username:  StartBootstrap
email_username:  Princessqyy@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
